### ISSUE TITLE
[FEAT] 미구현 기능 TODO 정리

### ISSUE THREAD

**Issue by Turtle-Hwan** [KUIT-Space/KUIT-Space-front#100]
# 필요 기능 TODO
## 주요기능
- [x] 게시판 #85
- [x] 스페이스 홈 뷰 #56 #31 #96 #95 
- [x] #111
- [x] #114
- [ ] 관리자 / 일반 멤버 관리 기능 | 전체 관리자 기능

## 세부기능 
_- [ ] 보이스룸 렌덤 아이콘_ -> 이거는 보류
- [ ] 스페이스 프로필 설정 / 수정 API 연동, 전체 프로필 수정 API
- [ ] 보이스룸 떠다니는 뷰
- [x] 로그아웃 API
- [x] 채팅방 파일 / 다운이 안돼!!!!1
  - [ ] 채팅방 파일 모바일에서 안올라가는 문제 [참고링크](https://velog.io/@cksrb63/React-FormData-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%97%85%EB%A1%9C%EB%93%9C-%EC%97%90%EB%9F%AC)
- [ ] 게시판 댓글 좋아요 / 대댓글 -> API 확인
- [ ] 게시글 공유 기능
- [ ] 정산 연동 #99

- [ ] 로그인 refreshToken 도입

### space 관련
- [ ] 스페이스 편집 / 위치 옮기기 (SpacePage.tsx)
  - [ ] 스페이스 초대 기능 / 자기 자신일 때 등 에러 핸들링
- [x] 스페이스 생성 (AddSpacePage.tsx)
- [x] 새 스페이스 이미지 선택 (AddSpacePage.tsx)
- [ ] 탈퇴하기(SpaceOption.tsx)

### user 관련
- [ ] 이름, 아이디, 비밀번호 변경 (AccountManage.tsx)
- [ ] 스페이스 프로필 관리 API (ProfileManage.tsx)

### pay 관련
- [ ] 토큰 만료되어도 로그인 모달에 도달하지 않는 경우 발생
- [ ] 정산 생성 결과가 response code 500을 반환해도 성공했다고 뜸. (에러 핸들링)

### homepage 관련
- [x] #104 진행 중(양석준)

## 작동은 하나 개선 필요한 것
- [x] #102
- [x] 내일 발표를 위한 스페이스 보이스룸 화상회의 준비

**Comment by Turtle-Hwan** [comment]
2.0으로 넘어갔으므로 이 이슈는 닫겠습니다
